import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from probabilistic_model.learning.jpt.variables import infer_variables_from_dataframe
from probabilistic_model.learning.jpt.jpt import JPT

def summarize_log_likelihood(ll_array: np.ndarray) -> tuple[float, float]:
    ll_array = np.asarray(ll_array)
    finite_lls = ll_array[np.isfinite(ll_array)]
    total_samples = len(ll_array)
    impossible_count = total_samples - len(finite_lls)
    impossible_percentage = (impossible_count / total_samples) * 100 if total_samples > 0 else 0
    if len(finite_lls) == 0:
        mean_finite_ll = -np.inf
    else:
        mean_finite_ll = np.mean(finite_lls)

    return mean_finite_ll, impossible_percentage

def main():
    np.random.seed(69)
    dist_1 = np.random.multivariate_normal(np.zeros((2,)), np.eye(2, 2), size=(200,))
    dist_2 = np.random.multivariate_normal(np.array([3, 4]), [[1, 2], [1, 0]], size=(300,))
    dataset = np.concatenate((dist_1, dist_2))
    dataset = pd.DataFrame(dataset, columns=["x", "y"])
    print("Sample dataset:")
    print(dataset.head())

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=dist_1[:, 0], y=dist_1[:, 1], mode="markers", name="First Component"))
    fig.add_trace(go.Scatter(x=dist_2[:, 0], y=dist_2[:, 1], mode="markers", name="Second Component"))
    fig.update_layout(title="Dataset generated by a mixture of two Multivariate Gaussians.")
    fig.write_html("dataset_plot.html")

    variables = infer_variables_from_dataframe(dataset, scale_continuous_types=False)
    model = JPT(variables, min_samples_leaf=500)
    pc = model.fit(dataset)
    pc.plot_structure()
    plt_pruned_name = "circuit_structure.png"
    plt.savefig(plt_pruned_name, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"\nOriginal PC has {len(list(pc.nodes()))} nodes and {len(list(pc.edges()))} edges.")
    mean_ll, impossible_percent = summarize_log_likelihood(pc.log_likelihood(dataset.values))
    print(f"- Mean log-likelihood {mean_ll:.3f}.")
    print(f"- Impossible samples {impossible_percent:.2f}%.")

    figure = go.Figure(pc.plot(number_of_samples=1000, surface=True))
    figure.update_layout(title="Learned Distribution")
    figure.write_html("learned_distribution_plot.html")

    pruned_pc = pc.prune(dataset.values, pruning_percentage=0.5)
    pruned_pc.plot_structure()
    plt_pruned_name = "circuit_structure_pruned.png"
    plt.savefig(plt_pruned_name, dpi=300, bbox_inches='tight')
    plt.close()
    mean_ll, impossible_percent = summarize_log_likelihood(pruned_pc.log_likelihood(dataset.values))
    print(f"\nPruned PC has {len(list(pruned_pc.nodes()))} nodes and {len(list(pruned_pc.edges()))} edges.")
    print(f"- Mean log-likelihood {mean_ll:.3f}.")
    print(f"- Impossible samples {impossible_percent:.2f}%.")

    grown_pc = pruned_pc.grow(noise_variance=0.1)
    grown_pc.plot_structure()
    plt_grown_name = "circuit_structure_grown.png"
    plt.savefig(plt_grown_name, dpi=300, bbox_inches='tight')
    plt.close()
    mean_ll, impossible_percent = summarize_log_likelihood(grown_pc.log_likelihood(dataset.values))
    print(f"\nGrown PC has {len(list(grown_pc.nodes()))} nodes and {len(list(grown_pc.edges()))} edges.")
    print(f"- Mean log-likelihood {mean_ll:.3f}.")
    print(f"- Impossible samples {impossible_percent:.2f}%.")

if __name__ == "__main__":
    main()
